on:
  pull_request:
   types: [opened, labeled, unlabeled, synchronize]

jobs:
  verify_pr_labels:
    runs-on: ubuntu-latest
    name: Verify that the PR has a valid label
    steps:
    - name: Verify Pull Request Labels
      uses: jesusvasquez333/verify-pr-label-action@master
      id: verify-pr-label
      with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'bug, enhancement, interface-change'
