on:
  pull_request_target:
   types: [opened, labeled, unlabeled, synchronize]

jobs:
  verify_pr_labels:
    runs-on: ubuntu-latest
    name: Verify that the PR has a valid label
    steps:
    - name: Verify Pull Request Labels
      #uses: jesusvasquez333/verify-pr-label-action@master
      uses: Pezmc/verify-pr-label-action@feature-disable-reviews
      id: verify-pr-label
      with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'bug, enhancement, interface-change'
          invalid-labels: 'help wanted, invalid'
          pull-request-number: '${{ github.event.pull_request.number }}'
          disable-reviews: true
