on:
  pull_request_target:
   types: [opened, labeled, unlabeled, synchronize]

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  verify_pr_labels:
    runs-on: ubuntu-latest
    name: Verify that the PR has a valid label
    steps:
    - name: Verify Pull Request Labels
      uses: jesusvasquez333/verify-pr-label-action@debug
      id: verify-pr-label
      with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'bug, enhancement, interface-change'
          pull-request-number: '${{ github.event.pull_request.number }}'
